version: "3.8"

services:
  postgres:
    container_name: boilerplate-go-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    image: postgres:15.1-alpine
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: boilerplate-go-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-golang:
    image: api-golang
    container_name: api-golang
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:

volumes:
  pgdata:
    external: true
    name: pgdata
